### ISSUE TITLE
Jupyter notebook

### ISSUE THREAD

**Issue by r-yamada1998** [KaoruNishikawa/obsparams#1]

**Comment by r-yamada1998** [comment]
I wonder if pyproject.toml includes the jupyter notebook module??

**Comment by KaoruNishikawa** [comment]
Currently no, and the notebook does work on my computer (both VSCode and browser.) But if you have any problem on running the notebook, I'll add it.

**Comment by r-yamada1998** [comment]
In my environment, the notebook does not work, So I installed the jupyter notebook to my environment, adding the notebook in the pyproject.toml,,,

**Comment by KaoruNishikawa** [comment]
I've added jupyter packages in #2 and if you still have the problem, please reopen this.

**Comment by r-yamada1998** [comment]
I do thank you.
